### ISSUE TITLE
Does note work here

### ISSUE THREAD

**Issue by zzAlfa** [ricardojoserf/instagram-followers-bot#16]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import aux_funcs, sys, json, time, random
  File "/data/data/com.termux/files/home/instagram-followers-bot/aux_funcs.py", line 1, in <module>
    import sys, json, requests, os
ImportError: No module named requests

**Comment by ricardojoserf** [comment]
Hi @zzAlfa !! That is because the Python library "requests" is not installed in your system. If you are using Python 2 you can use "pip install requests" and if using Python 3 "pip3 install requests"

In case you want to see other ways to do this you can see this Stackoverflow thread -> https://stackoverflow.com/questions/17309288/importerror-no-module-named-requests

Best regards,

Ricardo

**Comment by zzAlfa** [comment]
It still appears 😕

**Comment by TEKKEN199** [comment]
في اثنين، ٣١ أغسطس، ٢٠٢٠ في ١٢:٣٧ ص، كتب zzAlfa <notifications@github.com>:

**Comment by zzAlfa** [comment]
Now this appears
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from LevPasha.InstagramAPI import InstagramAPI
  File "/data/data/com.termux/files/home/instagram-followers-bot/LevPasha/InstagramAPI.py", line 21, in <module>
    from requests_toolbelt import MultipartEncoder
ModuleNotFoundError: No module named 'requests_toolbelt'
I already install requests with pip. 
This tool work on termux?

**Comment by TEKKEN199** [comment]
في اثنين، ٣١ أغسطس، ٢٠٢٠ في ١٢:٤٢ ص، كتب zzAlfa <notifications@github.com>
I am using python 3
and i love you 😀❤️🔥🔥

**Comment by zzAlfa** [comment]
Thanks man, its working
Actually i Discover that with python 3 i need to install requests_toolbelt.

**Comment by ricardojoserf** [comment]
Glad to hear it is working! I will close the issue :)
